apiVersion: alustan.io/v1alpha1
kind: App
metadata:
  name: dependent-service
spec:
  environment: staging
  source:
    repoURL: https://github.com/alustan/cluster-manifests
    path: basic-demo
    releaseName: basic-demo
    targetRevision: main
    values:
      nameOverride: dependent-service
      service: frontend
      image:
        repository: alustan/web-app-demo
        tag: "1.0.1"
      ingress:
        hosts:
          - host: dependent.localhost
      config:
        DUMMY_1: "{{.dummy_output_1}}"
        DUMMY_2: "{{.dummy_output_2}}"
  containerRegistry:
    provider: docker
    imageName: alustan/web-app-demo
    semanticVersion: ">=0.2.0"
  dependencies:
    service:
      - name: web-service
